# Generated by Django 6.0.1 on 2026-02-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=100)),
                ('Emp_Salary', models.FloatField()),
                ('Emp_Joining_Date', models.DateField(auto_now_add=True)),
                ('Emp_Age', models.IntegerField()),
                ('Emp_Post', models.CharField(max_length=100)),
            ],
        ),
    ]
