# Generated by Django 6.0.1 on 2026-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(max_length=50)),
                ('Course_code', models.CharField(max_length=50)),
                ('Duration', models.IntegerField()),
                ('Fees', models.IntegerField()),
                ('Is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
