# Generated by Django 6.0.1 on 2026-02-07 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('recovered', 'Recovered')], default='Lost')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=128)),
                ('user_phone', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating_given', to='Test.user')),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating_receive', to='Test.user')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('match', 'Match'), ('message', 'Message'), ('status', 'Status')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Test.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Test.user')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='lost_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('lost_date', models.DateField()),
                ('lost_time', models.TimeField()),
                ('status_lost', models.CharField(choices=[('open', 'Open'), ('recovered', 'Recovered')], default='Open')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.items')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.user')),
            ],
            options={
                'db_table': 'lost_reports',
            },
        ),
        migrations.CreateModel(
            name='found_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('found_date', models.DateField()),
                ('status_found', models.CharField(choices=[('available', 'Available'), ('claim', 'Claim')], default='Available', max_length=20)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.items')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.user')),
            ],
            options={
                'db_table': 'found_reports',
            },
        ),
    ]
