# Generated by Django 6.0.1 on 2026-02-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='found_reports',
            new_name='found_report',
        ),
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
        migrations.RenameModel(
            old_name='lost_reports',
            new_name='lost_report',
        ),
        migrations.RenameModel(
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameModel(
            old_name='notifications',
            new_name='notification',
        ),
        migrations.RenameModel(
            old_name='ratings',
            new_name='rating',
        ),
    ]
