# Generated by Django 6.0.1 on 2026-02-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(max_length=50)),
                ('Course_code', models.CharField(max_length=50)),
                ('Duration', models.IntegerField()),
                ('Fees', models.IntegerField()),
                ('Is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('internship_role', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_color', models.CharField(max_length=100)),
                ('Product_price', models.IntegerField()),
                ('Product_stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_Enroll', models.CharField(max_length=15)),
                ('student_age', models.PositiveIntegerField()),
                ('student_Email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
