# Generated by Django 6.0.1 on 2026-02-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField()),
                ('category_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('service_status', models.BooleanField(default=True)),
                ('service_discount', models.IntegerField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.category')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_hobbies', models.CharField(choices=[('Working', 'Working'), ('Music_Listning', 'Music_Listning'), ('Reading', 'Reading'), ('Singing', 'Singing'), ('Runnig', 'Running')], max_length=100)),
                ('student_address', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=10)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_dob', models.DateField()),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'studentprofile',
            },
        ),
    ]
