# Generated by Django 6.0.1 on 2026-02-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_category_service_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_price',
            field=models.FloatField(null=True),
        ),
    ]
