# Generated by Django 6.0.1 on 2026-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_color', models.CharField(max_length=100)),
                ('Product_price', models.IntegerField()),
                ('Product_stock', models.PositiveIntegerField()),
            ],
        ),
    ]
