# Generated by Django 6.0.1 on 2026-02-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_service_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_manufacture', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_fule', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100)),
                ('vehicle_engine_no', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='TrafficFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('offence', models.TextField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.vehicle')),
            ],
            options={
                'db_table': 'TrafficFine',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_center', models.CharField(max_length=100)),
                ('cost', models.FloatField(max_length=10)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.vehicle')),
            ],
            options={
                'db_table': 'ServiceRecord',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('insurer_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.vehicle')),
            ],
            options={
                'db_table': 'InsurancePolicy',
            },
        ),
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='vehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(default=True, max_length=20)),
                ('reg_date', models.DateField(default=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_address', models.TextField()),
                ('vehicle_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.vehicle')),
            ],
            options={
                'db_table': 'vehicleRegistration',
            },
        ),
    ]
